Repository B-AROL-O/ARNEIS, pull requests merged in 2022-02, with the labels that each got.

#114 [Fix] Adjust RPi 4B hostname
  docs/howto/howto-configure-rpi-poweredup.md
  docs/howto/howto-prepare-rpi4b-for-arneis.md
Labels: bug, documentation

#116 [Fix] DepthAI: Create virtualenv under virtualenv/
  docs/howto/howto-prepare-rpi4b-for-arneis.md
Labels: documentation, enhancement

#115 [Feat] docs/howto: Add howto-install-k3s-for-arneis.md
  docs/howto/howto-create-vm-on-azure.md
  docs/howto/howto-install-k3s-for-arneis.md
  docs/images/k3s-architecture-single-server.png
  docs/index.rst
Labels: documentation, enhancement

#118 [Docs] howto-install-k3s-for-arneis.md: Fix typo
  docs/howto/howto-install-k3s-for-arneis.md
Labels: bug, documentation

#125 [Feat] First shot at ARNEIS System Architecture document
  docs/architecture/arneis-sysarch.md
  docs/architecture/diagrams/sample-network-citrix.drawio
  docs/architecture/diagrams/sample-uml-sysml.svg
  docs/index.rst
Labels: documentation, enhancement

#102 [Feat] Embed YouTube video inside ARNEIS documentation
  README.md
  docs/index.rst
Labels: documentation, enhancement

#126 [Feat] Misc improvements to toplevel README.md
  README.md
Labels: documentation, enhancement

#127 Add How-To train and deploy NN
  docs/howto/howto-train-deploy-NN.md
  docs/index.rst
Labels: documentation, enhancement

#129 OAK-D-Lite LEGO adapter
  docs/images/oak-d-lite-lego-support-01.jpg
  docs/images/oak-d-lite-lego-support-02.jpg
  docs/images/oak-d-lite-lego-support-03.jpg
  docs/images/oak-d-lite-lego-support-04.jpg
  docs/images/oak-d-lite-lego-support-05.jpg
  mocs/studies/camera-support/README.md
  mocs/studies/camera-support/oak-d-lite-support.io
  mocs/studies/camera-support/oak-d-lite-support.ldr
  mocs/studies/camera-support/oak-d-lite-support.png
Labels: documentation, enhancement

#136 [Feat] howto-train-deploy-NN.md: Show training results
  docs/howto/howto-train-deploy-NN.md
Labels: documentation, enhancement

#137 [Fix] index.rst: Rearrange ToC
  docs/index.rst
Labels: bug, documentation

#148 [Feat] Refactor "Install DepthAI on RPi" into a separate document
  .vscode/settings.json
  docs/howto/howto-install-depthai-on-rpi.md
  docs/howto/howto-prepare-rpi4b-for-arneis.md
  docs/index.rst
Labels: documentation

#155 [Feat] docs: Add bibliography.md
  docs/bibliography.md
  docs/index.rst
Labels: documentation, enhancement

#164 [Feat] Update docs/bibliography.md
  docs/bibliography.md
Labels: documentation, enhancement

#165 [Feat] docs: Add page with acronyms
  docs/acronyms.md
  docs/index.rst
Labels: documentation, enhancement

#166 Add link to /docs subfolder
  README.md
Labels: documentation

#167 [Feat] Improve docs/bibliography.md
  .github/linters/.gitleaks.toml
  docs/bibliography.md
Labels: documentation, enhancement

#168 [Bugfix] index.rst: Comment out :ref:`modindex`
  docs/index.rst
Labels: bug, documentation

#173 Complete bags 2
  docs/lego-set-42100/unboxing-lego-set-42100.md
Labels: enhancement, :bricks: LEGO

#178 [Feat] Complete inventory of LEGO Set 42100 Bags #1
  docs/lego-set-42100/unboxing-lego-set-42100.md
Labels: documentation, enhancement, :bricks: LEGO

#176 [Feat] Expand arneis-sysarch
  docs/architecture/arneis-sysarch.md
Labels: documentation, enhancement

#180 [Feat] Verify contents of LEGO 42100 bag set 2
  docs/lego-set-42100/unboxing-lego-set-42100.md
Labels: documentation

#183 [Feat] First attempt at arneis-swarch.md
  docs/architecture/arneis-swarch.md
  docs/index.rst
Labels: documentation, enhancement, help wanted

#181 [Feat] First attempt at reorganizing arneis.readthedocs.io index
  .vscode/settings.json
  docs/conf.py
  docs/index.rst
  docs/lego/camera-support.md
  docs/lego/studies.md
  mocs/studies/camera-support/README.md
Labels: documentation

#187 [Fix] Troubleshoot arneis.RTD build failure
  docs/conf.py
Labels: bug, documentation, help wanted

#190 Disable PDF generation from readthedocs site
  .readthedocs.yaml
Labels: bug

#193 add Gitpod launcher
  README.md
Labels: enhancement

#195 [Fix] Fix Bug/194: wide table handling
  .github/workflows/linter.yml
  docs/_static/theme_overrides.css
  docs/_templates/layout.html
Labels: bug, documentation

#197 [Feat] LEGO 42100 Bags 3
  docs/lego-set-42100/unboxing-lego-set-42100.md
Labels: documentation, enhancement, :bricks: LEGO

#198 [Feat] Expand contents of docs/acronyms.md
  docs/acronyms.md
  docs/architecture/arneis-spec.md
Labels: documentation, enhancement

#199 [Fix] Check and update BOM for Bag 3A, 3B, 3C, 3C1, 3D
  docs/lego-set-42100/unboxing-lego-set-42100.md
Labels: documentation, :bricks: LEGO

#200 [Feat] Add `Python library to interact with Move Hub...`
  docs/bibliography.md
Labels: documentation, :bricks: LEGO

#202 [Fix] README.md: Use a consistent Gitpod badge
  README.md
Labels: documentation, enhancement

#205 [Feat] Complete LEGO Set 42100 Bags 4
  docs/lego-set-42100/unboxing-lego-set-42100.md
Labels: documentation, :bricks: LEGO

#203 [Fix] Check contents of LEGO Set 42100 Bags 3D1, 3E, 3E1, 3E2, 3F
  docs/lego-set-42100/unboxing-lego-set-42100.md
Labels: documentation, :bricks: LEGO

#209 [Feat] Add contents of LEGO Set 42100 Bags #5
  docs/lego-set-42100/unboxing-lego-set-42100.md
Labels: documentation, :bricks: LEGO

#210 [Fix] unboxing-lego-set-42100.md: Remove redundant text
  docs/lego-set-42100/unboxing-lego-set-42100.md
Labels: bug, documentation, :bricks: LEGO

#212 [Feat] Add contents of LEGO Set 42100 Bags #6
  docs/lego-set-42100/unboxing-lego-set-42100.md
Labels: documentation, :bricks: LEGO

#177 [Feat] Expand howto-control-rpi-poweredup.md
  code/pybricks-test01/main.py
  code/pybricks-test01/requirements.txt
  docs/bibliography.md
  docs/howto/howto-control-rpi-poweredup.md
Labels: documentation, enhancement, :bricks: LEGO

#215 [Fix] Typo: s/Raspberrry/Raspberry/
  docs/howto/howto-control-rpi-poweredup.md
Labels: bug, documentation, :bricks: LEGO

#217 [Feat] Add .svg logo for the ARNES project
  docs/images/Arneis_logo_.svg
Labels: documentation, enhancement
