Repository B-AROL-O/ARNEIS, pull requests merged in 2022-04, with the labels that each got.

#289 README.md: Fix spelling in ARNEIS acronym definition
  README.md
  docs/index.rst
Labels: bug, documentation, help wanted

#281 [FEAT] Prepare ARNEIS System Integration Document
  docs/images/2022-03-26-1855-arneis-sysint.jpg
  docs/index.rst
  docs/sysint/arneis-sysint-1.0.md
Labels: documentation, enhancement

#292 README.md: Refactor home page with new contents and structure
  README.md
Labels: documentation, enhancement, help wanted

#294 enable pdf export
  .readthedocs.yaml
Labels: bug, documentation

#295 [Fix] README.md: Update length of ARNEIS submission Video
  README.md
Labels: documentation, enhancement

#298 [Feat] Add ARNEIS icon and QR Codes
  docs/images/arneis-icon.png
  docs/images/arneis-qr-code-white-on-red.png
  docs/images/arneis-qr-code-white-on-red.svg
  docs/images/arneis-qr-code.png
  docs/images/arneis-qr-code.svg
Labels: documentation, enhancement

#300 [Feat] arneis.rtd: Add list of posts on social media
  docs/arneis-social-media.md
  docs/index.rst
Labels: documentation, enhancement, help wanted

#303 Add arneis-call-to-action PDF
  docs/images/arneis-call-to-action.pdf
Labels: documentation

#302 [Feat] index.rst: Refactor contents
  docs/arneis-social-media.md
  docs/index.rst
Labels: documentation, enhancement, help wanted

#297 [FEAT] docs: Add Dockerfile
  docs/Dockerfile
  docs/README.md
Labels: enhancement

#305 [Feat] arneis-social-media: Add contents
  docs/arneis-social-media.md
Labels: documentation, enhancement

#307 [Feat] docs: Create howto-use-mermaid-graphic-tool.md
  docs/howto/howto-use-mermaid-graphic-tool.md
Labels: documentation, enhancement

#306 [Feat] arneis-social-media.md: New tweets and LinkedIn posts
  docs/arneis-social-media.md
Labels: documentation, enhancement

#308 [Feat] docs/howto: Add howto-testing-portenta-x8.md
  docs/howto/howto-testing-portenta-x8.md
Labels: documentation, enhancement

#277 [Feat] docs: Add howto-rpi3p-raspios64
  docs/howto/howto-install-raspios64.md
  docs/images/2022-03-26-1019-k9s.png
  docs/images/2022-03-27-2137-k9s-describe.png
Labels: documentation, enhancement

#311 [Feat] docs/social-media-presence: Add new links
  docs/arneis-social-media.md
  docs/howto/howto-control-rpi-poweredup.md
Labels: documentation, enhancement

#312 Add section: Inspect the host OS on the Portenta X8
  docs/arneis-social-media.md
  docs/bibliography.md
  docs/howto/howto-testing-portenta-x8.md
Labels: documentation, enhancement

#314 [Feat] New tweet by @gpmacario
  docs/arneis-social-media.md
Labels: documentation

#313 [Feat] New document hierarchy
  docs/index.rst
Labels: documentation, enhancement

#315 [Feat] docs/images: Add 2022-04-21-opencv-spatial-ai-contest-top-10-finalist.png
  docs/images/2022-04-21-opencv-spatial-ai-contest-top-10-finalist.png
Labels: documentation, enhancement, help wanted

#316 [Fix] New images stored in /docs/images
  docs/howto/howto-configure-arneis-readthedocs-io.md
  docs/images/2022-04-21-2157-howto-rtd-admin.png
  docs/images/2022-04-21-2157-howto-rtd-advsetting.png
  docs/images/2022-04-21-2157-howto-rtd-pr-detail.png
Labels: bug

#317 [Feature] Call-to-vote for ARNEIS
  README.md
  docs/index.rst
Labels: documentation, enhancement, help wanted

#318 [Feat] Update arneis-social-media.md
  .github/workflows/check-links.yml
  docs/arneis-social-media.md
Labels: documentation, enhancement, help wanted

#319 [Feat] Update arneis-social-media
  docs/arneis-social-media.md
  docs/howto/howto-train-deploy-NN.md
Labels: documentation
