Repository B-AROL-O/ARNEIS, pull requests merged in 2022-05, with the labels that each got.

#321 [Feat] Update arneis-social-media.md
  docs/arneis-social-media.md
Labels: documentation, enhancement

#322 [Feat] HOWTO: Add howto-getting-started-foundriesio
  docs/howto/howto-getting-started-foundriesio.md
  docs/images/2022-04-30-0911-fio-factories-test-fio-raspi4.png
  docs/index.rst
Labels: documentation, enhancement

#323 howto-install-raspios64: Add section: Update the Bootloader of the Raspberry Pi
  docs/howto/howto-install-raspios64.md
  docs/images/2022-05-01-1948-install-os-raspi.jpg
  docs/images/2022-05-01-2010-embedded-raspi-imager.jpg
Labels: documentation, enhancement

#324 [Feat] Update arneis-social-media
  docs/arneis-social-media.md
Labels: documentation, enhancement

#296 [Feat] LEGO Control+ image
  docs/images/2022-04-02_Lego-control+.jpeg
Labels: enhancement, help wanted

#304 Adapt conveyor Pybricks source code - San Mauro, 2022-04-09
  code/pybricks-test01/README.md
  code/pybricks-test01/main2.py
Labels: documentation, enhancement

#327 arneis-social-media: New @alv67 post on LinkedIn
  .github/linters/.gitleaks.toml
  docs/arneis-social-media.md
Labels: documentation, enhancement

#330 [Feat] update-howto-portenta-x8: Managed to scan nearby BLE devices
  docs/howto/howto-testing-portenta-x8.md
Labels: documentation, enhancement

#329 arneis-social-media: Project Status Report for dev-cw18 is out
  docs/arneis-social-media.md
Labels: documentation, enhancement

#331 [Feat] Update HOWTO: Getting started with Foundries.io
  docs/howto/howto-getting-started-foundriesio.md
  docs/images/2022-05-11-1159-fio-targets.png
  docs/images/2022-05-11-1202-fio-target-details.png
  docs/images/2022-05-11-1205-fio-target-run-details.png
  docs/images/2022-05-11-1953-fio-activate.png
  docs/images/2022-05-11-1954-fio-activate-confirm.png
  docs/images/2022-05-11-1956-fio-activate-complete.png
  docs/images/2022-05-11-1958-fio-devices.png
  docs/images/2022-05-11-2002-fio-device-rpird102.png
Labels: documentation, enhancement

#335 [Feat] New gpmacario tweet about latest ARNEIS Project Status Report
  docs/arneis-social-media.md
Labels: documentation, enhancement

#333 [Feat] Foundries.io: Deploy your first Application
  docs/howto/howto-getting-started-foundriesio.md
  docs/images/2022-05-16-1217-source-foundries-io.png
  docs/images/2022-05-17-0716-hello-world.png
Labels: documentation, enhancement

#338 [Fix] bibliography.md: Remove entry with dead link
  docs/bibliography.md
Labels: bug, documentation

#336 [docs] Tweet about Release 1.0 of the ARNEIS project
  docs/arneis-social-media.md
Labels: documentation, enhancement

#339 [Feat] Update arneis-social-media.md
  docs/arneis-social-media.md
Labels: documentation, enhancement
