Repository B-AROL-O/ARNEIS, pull requests merged in 2022-06, with the labels that each got.

#341 Remove request for a vote from arneis.readthedocs.io
  docs/index.rst
Labels: documentation

#342 Fix link to ARNEIS project pitch at OpenCV Spatial AI Contest Top 10
  docs/arneis-social-media.md
Labels: bug, documentation

#343 [Feat] Replace logo with "Winner of the Popular Vote"
  README.md
  docs/images/2022-06-14-opencv-spatial-ai-contest-popular-vote-winner.jpg
Labels: documentation, enhancement
