Repository B-AROL-O/ARNEIS, pull requests merged in 2022-03, with the labels that each got.

#218 Add chapter: Interfacing an input sensor
  docs/bibliography.md
  docs/howto/howto-control-rpi-poweredup.md
Labels: documentation, enhancement, :bricks: LEGO

#216 [Fix] Verify LEGO Set 42100 Bags 5
  docs/lego-set-42100/unboxing-lego-set-42100.md
Labels: documentation, :bricks: LEGO

#220 [Feat] Expand howto-install-k3s-for-arneis
  docs/acronyms.md
  docs/howto/howto-install-k3s-for-arneis.md
Labels: documentation, enhancement

#222 [Feat] Expand bibliography
  docs/bibliography.md
Labels: documentation, enhancement

#223 [FEAT] lego parts converter csv to md
  code/lego-parts-csv2md/README.md
  code/lego-parts-csv2md/partlist-csv2md.ipynb
  code/lego-parts-csv2md/test.csv
Labels: enhancement, :bricks: LEGO

#224 [Feat] bibliography.md: Add links for communication Raspberry Pi-LEGO
  docs/bibliography.md
Labels: documentation, enhancement, :bricks: LEGO

#228 [Feat] Complete the ARNEIS K3s cluster installation
  docs/howto/howto-install-k3s-for-arneis.md
Labels: documentation, enhancement

#227 [Feat] Expand howto-control-rpi-poweredup
  docs/acronyms.md
  docs/howto/howto-control-rpi-poweredup.md
Labels: documentation, enhancement, :bricks: LEGO

#230 [Feat] howto-install-k3s-for-arneis: Reorganize chapters
  docs/howto/howto-install-k3s-for-arneis.md
Labels: documentation, enhancement

#233 [Feat] Add sample project for the LEGO Powered Up App
  code/poweredupapp-flash-move/README.md
  code/poweredupapp-flash-move/program.json
  code/poweredupapp-flash-move/thumbnail.png
  docs/bibliography.md
Labels: enhancement, :bricks: LEGO

#231 [FEAT] CAD project v.20220312
  mocs/project/README.md
  mocs/project/arneis-conveyor-20220312.io
  mocs/project/arneis-conveyor-20220312.ldr
  mocs/project/arneis-conveyor-20220312.png
Labels: documentation, enhancement, :bricks: LEGO

#235 README.md: Fix broken link
  mocs/project/README.md
Labels: bug, documentation, :bricks: LEGO

#237 [BUGFIX] two typos in build instruction doc
  mocs/project/arneis-conveyor-20220312.io
Labels: bug, documentation, :bricks: LEGO

#240 [Feat] poweredupapp-flash-move: Minor improvements
  code/poweredupapp-flash-move/README.md
Labels: documentation, enhancement, :bricks: LEGO

#243 [Feat] Sanitize all links in the ARNEIS codebase
  .github/workflows/check-links.yml
  README.md
  docs/architecture/arneis-spec.md
  docs/architecture/arneis-sysarch.md
  docs/bibliography.md
  docs/howto/howto-configure-arneis-readthedocs-io.md
  docs/howto/howto-control-rpi-poweredup.md
  docs/howto/howto-install-depthai-on-windows10.md
  docs/howto/howto-install-k3s-for-arneis.md
  docs/howto/howto-prepare-rpi4b-for-arneis.md
  docs/lego-set-42100/unboxing-lego-set-42100.md
  mocs/project/README.md
Labels: enhancement

#245 bibliography: Add more links about LEGO Powered Up
  docs/bibliography.md
Labels: documentation, enhancement, :bricks: LEGO

#248 docs/index.rst: Align with latest updates in toplevel README.md
  .vscode/settings.json
  docs/index.rst
Labels: documentation, enhancement

#252 [Fix] index.rst: Fix the &reg; symbol
  docs/index.rst
Labels: bug, documentation

#254 [Feat] docs/architecture: Update arneis-swarch.md
  docs/architecture/arneis-swarch.md
Labels: documentation, enhancement

#247 [Feat] README.md: Embed latest ARNEIS YouTube video
  README.md
Labels: documentation, enhancement

#275 [Feat] README.md: Clarify License
  README.md
Labels: documentation, enhancement

#274 howto-install-depthai-on-rpi: Correct link text
  docs/howto/howto-install-depthai-on-rpi.md
Labels: bug, documentation

#270 [Feat] docs: Expand bibliography.md
  docs/bibliography.md
Labels: documentation, enhancement

#285 [Feat] index.rst: Embed YT video: OpenCV Weekly Webinar Ep.49
  docs/index.rst
Labels: enhancement, help wanted

#286 Complete how to train NN
  docs/howto/howto-train-deploy-NN.md
Labels: documentation, enhancement
