Repository B-AROL-O/ARNEIS, pull requests merged in 2022-01, with the labels that each got.

#11 [Fix] howto-prepare-rpi4b-for arneis: Improve text, add more pics
  docs/howto/howto-prepare-rpi4b-for-arneis.md
  docs/images/2022-01-13-1731-vnc-connect.png
  docs/images/2022-01-13-1736-vnc-connect-rpi4gm35.png
Labels: documentation

#25 [docs] Add section: ARNEIS is an OpenCV Spatial AI Contest Finalist
  README.md
  docs/images/2021-12-17-1832-opencv-spatial-ai-contest-finalist.jpg
Labels: documentation

#27 [Fix] README.md: Remove spurious characters from URL
  README.md
Labels: bug

#41 LICENSE: Extend Copyright year to 2022
  LICENSE
Labels: documentation

#39 New improved B-AROL-O logo, issue #35
  docs/images/Barolo_logo_shade.svg
Labels: enhancement

#49 [WIP] First conveyor draft
  mocs/studies/Conveyor_001.ldr
  mocs/studies/Conveyor_001.png
Labels: enhancement

#62 [Fix] Enable the "Single quotes" option feature for Black
  .github/linters/.python-black
Labels: enhancement

#63 [Feat] Configure Sphinx for automatic document generation
  .github/linters/.python-black
  .github/linters/.textlintrc
  .gitignore
  .vscode/settings.json
  docs/Makefile
  docs/conf.py
  docs/howto/howto-configure-arneis-readthedocs-io.md
  docs/index.rst
  docs/make.bat
Labels: documentation, enhancement

#64 [Feat] Improve document generation
  .vscode/settings.json
  README.md
  docs/conf.py
  docs/index.rst
  docs/requirements.txt
Labels: documentation, enhancement

#60 [Feat] howto-prepare-rpi4b-for-arneis: Add section: Install and run DepthAI
  docs/howto/howto-prepare-rpi4b-for-arneis.md
Labels: documentation, enhancement

#73 Update Sphinx configuration
  docs/conf.py
  docs/requirements.txt
Labels: documentation, enhancement

#58 Create test_multiple_OAKD.py
  code/test_multiple_OAKD.py
Labels: enhancement

#81 [Feat] Install git-aware-prompt
  docs/howto/howto-prepare-rpi4b-for-arneis.md
Labels: documentation, enhancement

#84 [Feat] docs/howto: Add howto-depthai-win10
  docs/howto/howto-install-depthai-on-windows10.md
  docs/index.rst
Labels: documentation, enhancement

#91 [Feat] Document how to enable ReadTheDocs preview for Pull Requests
  docs/howto/howto-configure-arneis-readthedocs-io.md
Labels: documentation, enhancement

#94 [Feat] docs/architecture: Add arneis-spec.md
  docs/architecture/arneis-spec.md
  docs/index.rst
Labels: documentation, enhancement

#97 [Feat] howto-configure-arneis-readthedocs-io: Add section: Removing the Ads
  docs/howto/howto-configure-arneis-readthedocs-io.md
Labels: documentation, enhancement

#99 [Feat] Improve howto-prepare-rpi4b-for-arneis
  docs/howto/howto-prepare-rpi4b-for-arneis.md
Labels: documentation, enhancement

#100 [Feat] docs/howto: Create howto-configure-rpi-poweredup.md
  docs/howto/howto-configure-rpi-poweredup.md
Labels: documentation, enhancement

#101 [Feat] Improve ARNEIS homepage on ReadTheDocs
  docs/index.rst
Labels: documentation, enhancement

#105 README.md: Embed video of the Bottle Conveyor
  README.md
Labels: documentation, enhancement

#107 Bottle capture area and an idea for gearing
  mocs/studies/bottle-conveyor-20220130.io
  mocs/studies/bottle-conveyor-20220130.ldr
  mocs/studies/bottle-conveyor-gearing-idea.png
  mocs/studies/bottle-conveyor-img-capture-area.png
Labels: enhancement

#111 [Feat] Add howto-create-vm-on-azure.md
  docs/howto/howto-create-vm-on-azure.md
  docs/index.rst
Labels: documentation, enhancement

#112 [Fix] howto-create-vm-on-azure: Add private-key-path after option "-i" to ssh
  docs/howto/howto-create-vm-on-azure.md
Labels: bug, documentation

#113 [Fix] Normalize Titles and ToC of documents under docs/howto
  docs/howto/howto-configure-arneis-readthedocs-io.md
  docs/howto/howto-install-depthai-on-windows10.md
  docs/howto/howto-prepare-rpi4b-for-arneis.md
Labels: bug, documentation
