Repository B-AROL-O/ARNEIS, pull requests merged in 2023-10, with the labels that each got.

#365 [FEAT]: Add CONTRIBUTING.md and CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation, enhancement, help wanted

#359 [FEAT]: howto: Add howto-install-eclipse-capella
  docs/howto/howto-configure-arneis-readthedocs-io.md
  docs/howto/howto-install-eclipse-capella.md
  docs/index.rst
Labels: documentation, enhancement

#366 [FEAT]: Add .devcontainer/devcontainer.json
  .devcontainer/devcontainer.json
  .github/linters/.eslintrc.yml
Labels: enhancement

#368 [FEAT] docs: Expand howto-install-eclipse-capella.md
  docs/howto/howto-install-eclipse-capella.md
Labels: documentation, hacktoberfest

#369 [FEAT]: code/lego-parts-csv2md: Minor improvements to README.md
  code/lego-parts-csv2md/README.md
Labels: bug, documentation
